version: '3.8'

services:
  watchtower:
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
